### ISSUE TITLE
Explain relationship to cryptsetup-reencrypt

### ISSUE THREAD

**Issue by tgr** [johndoe31415/luksipc#13]
Searching for in-place encryption of hard disks brings up luksipc and cryptsetup-reencrypt, but I didn't find anything that compares them (or even mentions both). It would be nice if the readme addressed what benefits/drawbacks this tool has compared to cryptsetup-reencrypt.

**Comment by johndoe31415** [comment]
Sorry for responding so incredibly late on this. I've somehow forgotten about this and just checked all my open issues.

The thing is, back when I started luksipc (version 0.01 is from 2011-10-15), there was no other tool to do this job. I wanted to have one, therefore I wrote it. I've just checked out the git repo and cryptsetup_reencrypt (back then known as crypt_reencrypt) was added my Milan Broz on 2012-05-02 ( 2fcb521c). It was marked as "non-experimental" in 2015-10-29. I've never used it -- but, to be honest, it may be easier to use it instead of luksipc. Firstly, it's supported and maintained by LUKS upstream, i.e., the tools will always "fit together" properly. Secondly, it uses the dmsetup library instead of the cryptsetup command line tool (which seems to be the better choice). Lastly and most importantly: It already comes with cryptsetup, i.e., you'll very likely already have cryptsetup-reencrypt installed when you install the LUKS userpsace tools. That's probably the biggest advantage.

Apart from those thoughts, I cannot really judge advantages and disadvantages precisely because I haven't used cryptsetup-reencrypt -- but if I was in your shoes, I'd probably go for cryptsetup-reencrypt. I surely wouldn't have written luksipc if there would've been an alternative around back then.
